//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UczelniaWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Marks
    {
        public Nullable<decimal> mark_value { get; set; }
        public string subject_name { get; set; }
        public string t_name { get; set; }
        public string surname { get; set; }
        public Nullable<int> student_id { get; set; }
        public int id { get; set; }
        public string username { get; set; }
    }
}
